### ISSUE TITLE
TypeError: data type "float128" not understood

### ISSUE THREAD

**Issue by wakame1367** [regonn/polar_bear#4]
Since the following error occurred during test execution, we will report it along with environmental information.
テスト実行時以下のエラーが発生したので環境情報と共に報告いたします。

### Python
- Python 3.6.6
### Machine_Enviroment
- OS  
  - Windows 10 64bit
### Package
- Name: pandas
  - Version: 0.23.4
- Name: numpy
  - Version: 1.15.3

### ErrorLog
```
Error
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\unittest\case.py", line 605, in run
    testMethod()
  File "C:\Users\***\PycharmProjects\polar_bear\tests\test_polar_bear.py", line 15, in test_clean
    train_df, test_df, target_col, 0.5)
  File "C:\Users\***\PycharmProjects\polar_bear\polar_bear\main.py", line 128, in clean
    return_df = _make_return_df(train_df, test_df, threshold_one_hot)
  File "C:\Users\***\PycharmProjects\polar_bear\polar_bear\main.py", line 67, in _make_return_df
    elif dtype in float_dtype_list:
TypeError: data type "float128" not understood
```

**Comment by regonn** [comment]
https://github.com/pandas-dev/pandas/issues/17809#issuecomment-335017208

> `float128` is not offically supported (nor on all platforms), so this actually is a more general issue.

So I will remove it soon.
